const EXPECTED_SECOND_MS = 1000;
export const EXPECTED_MINUTE_MS = EXPECTED_SECOND_MS * 60;
export const EXPECTED_HOUR_MS = EXPECTED_MINUTE_MS * 60;
export const EXPECTED_BUSINESS_DAY_MS = EXPECTED_HOUR_MS * 8;
export const EXPECTED_BUSINESS_WEEK_MS = EXPECTED_BUSINESS_DAY_MS * 5;
