import styles from './PrivacyPolicy.module.scss';

// Atlassian requires to have a page dedicated to app's Privacy Policy
// this policy was generated by ChatGPT
export const PrivacyPolicy = () => (
  <main className={styles.privacyPolicy}>
    <h1>Privacy Policy</h1>
    <p>
      <strong>Last updated:</strong> 19.08.2024
    </p>

    <p>
      Your privacy is important to us. This Privacy Policy explains how &quot;Timesheet&quot; (the &quot;App&quot;)
      collects, uses, and protects your personal information when you use the App. By using the App, you agree to the
      practices outlined in this Privacy Policy.
    </p>

    <h2>1. Information We Collect</h2>
    <p>
      The App accesses Atlassian&#8217;s user data through its API. The specific data accessed is limited to that which
      is necessary for the App to function effectively. The data accessed may include, but is not limited to, user
      information from Atlassian platforms.
    </p>

    <h2>2. How We Use Your Data</h2>
    <p>
      The data accessed from Atlassian is used solely to enable the core functionality of the App. This may include, but
      is not limited to, tracking time, managing tasks, or other time-related activities.
    </p>

    <p>
      We do <strong>not</strong> use your data for any other purpose, such as marketing, analytics, or profiling.
    </p>

    <h2>3. Data Storage and Security</h2>
    <p>
      All data accessed through the App is stored <strong>locally in your browser&#8217;s Local Storage</strong>. We do
      not store or process any of your data on external servers or cloud services.
    </p>

    <p>
      While we take reasonable precautions to protect the security of your data, it is important to note that you are
      responsible for ensuring the security of your device and browser environment.
    </p>

    <h2>4. User Control and Rights</h2>
    <p>
      Since all data is stored locally in your browser&#8217;s Local Storage, you have full control over it. You can
      modify, delete, or clear your Local Storage at any time through your browser&#8217;s settings.
    </p>

    <p>
      We do not retain any of your data ourselves and therefore cannot respond to requests for data access, correction,
      or deletion.
    </p>

    <h2>5. Third-Party Sharing</h2>
    <p>
      We do <strong>not</strong> share your data with any third parties. The data accessed by the App remains in your
      browser&#8217;s Local Storage and is not transmitted to external servers or entities.
    </p>

    <h2>6. Cookies and Tracking</h2>
    <p>
      The App uses cookies that are strictly necessary for its core functionality. These cookies are used exclusively to
      support the operation of the App and do not serve any tracking, marketing, or analytical purposes.
    </p>

    <h2>7. Children’s Privacy</h2>
    <p>
      The App is not directed to children under the age of 13. We do not knowingly collect personal data from children.
    </p>

    <h2>8. Changes to This Privacy Policy</h2>
    <p>
      We may update this Privacy Policy from time to time to reflect changes in our practices or for other operational,
      legal, or regulatory reasons. We encourage you to review this policy periodically for any updates.
    </p>
  </main>
);
