import styles from './PrivacyPolicy.module.scss';

// Atlassian requires to have a page dedicated to app's Privacy Policy
// https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps/#overview
// Generated by Claude Sonnet 4
export const PrivacyPolicy = () => (
  <main className={styles.privacyPolicy}>
    <h1>Privacy Policy</h1>
    <p>
      <strong>Last updated:</strong> August 13, 2025
    </p>

    <p>
      Your privacy is important to us. This Privacy Policy explains how the &quot;Timesheet&quot; application (the
      &quot;App&quot;) collects, uses, and protects your personal information when you use the App. By using the App,
      you agree to the practices outlined in this Privacy Policy.
    </p>

    <h2>1. About the Application</h2>
    <p>
      Timesheet is a time tracking application that integrates with Atlassian Jira and Yandex Tracker. The App helps
      users track time spent on tasks, manage worklogs, and generate time reports for project management purposes.
    </p>

    <h2>2. Information We Collect</h2>
    <p>
      The App accesses data from your connected services through their APIs using OAuth 2.0 authorization. The specific
      data accessed includes:
    </p>

    <h3>From Jira (Atlassian):</h3>
    <ul>
      <li>User account information (account ID, email address, display name, account type)</li>
      <li>Issue data (issue keys, summaries, status, assigned users)</li>
      <li>Worklog entries (time entries, comments, timestamps)</li>
      <li>Project and queue information</li>
      <li>Organization and workspace details</li>
    </ul>

    <h3>From Yandex Tracker:</h3>
    <ul>
      <li>User profile information</li>
      <li>Task and issue data</li>
      <li>Time tracking records</li>
      <li>Project and queue information</li>
    </ul>

    <h2>3. How We Use Your Data</h2>
    <p>
      The data accessed from Jira and Yandex Tracker is used exclusively to provide the App&apos;s core functionality:
    </p>
    <ul>
      <li>Displaying tasks and issues from your connected services</li>
      <li>Creating, editing, and deleting time tracking entries</li>
      <li>Generating time reports and summaries</li>
      <li>Managing pinned tasks and user preferences</li>
      <li>Filtering and organizing tasks by various criteria</li>
    </ul>
    <p>
      We do <strong>not</strong> use your data for any other purposes, such as marketing, analytics, profiling, or
      sharing with third parties.
    </p>

    <h2>4. Data Storage and Security</h2>
    <p>
      All data accessed through the App is processed and stored{' '}
      <strong>locally in your browser&apos;s Local Storage</strong>. Specifically:
    </p>
    <ul>
      <li>Authentication tokens are stored locally for secure API access</li>
      <li>User preferences and pinned tasks are saved in browser storage</li>
      <li>Cached task and project data is stored temporarily for performance</li>
      <li>Language and locale preferences are stored locally</li>
    </ul>
    <p>
      We do <strong>not</strong> store, process, or transmit any of your personal data to external servers or cloud
      services beyond the necessary API calls to your connected services (Jira/Yandex Tracker).
    </p>

    <h2>5. Authentication and Access</h2>
    <p>
      The App uses OAuth 2.0 protocols to securely authenticate with Jira and Yandex Tracker. Your login credentials are
      never stored or processed by our App. Authentication tokens are stored locally and are used only to make
      authorized API requests to your connected services.
    </p>

    <h2>6. User Control and Rights</h2>
    <p>You have complete control over your data:</p>
    <ul>
      <li>All data is stored locally in your browser - you can clear it at any time through browser settings</li>
      <li>
        You can revoke the App&apos;s access to your Jira/Yandex Tracker accounts through your account settings in those
        services
      </li>
      <li>You can disconnect trackers and remove all associated data from the App</li>
      <li>You can modify or delete individual time entries and preferences within the App</li>
    </ul>
    <p>
      Since we do not retain any of your data on external servers, we cannot respond to requests for data access,
      correction, or deletion - you have direct control through your browser and connected services.
    </p>

    <h2>7. Third-Party Services</h2>
    <p>The App connects to and retrieves data from:</p>
    <ul>
      <li>
        <strong>Atlassian Jira:</strong> For issue tracking and worklog management
      </li>
      <li>
        <strong>Yandex Tracker:</strong> For task management and time tracking
      </li>
    </ul>
    <p>
      Your use of these services is subject to their respective privacy policies. We recommend reviewing the privacy
      policies of Atlassian and Yandex for information about how they handle your data.
    </p>

    <h2>8. Cookies and Local Storage</h2>
    <p>The App uses browser Local Storage and cookies that are strictly necessary for its core functionality:</p>
    <ul>
      <li>Authentication tokens and session management</li>
      <li>User preferences and application settings</li>
      <li>Cached data for improved performance</li>
      <li>Language and locale settings</li>
    </ul>
    <p>
      These storage mechanisms do not serve any tracking, marketing, or analytical purposes beyond the App&apos;s
      functionality.
    </p>

    <h2>9. Data Retention</h2>
    <p>Data is retained locally in your browser until you:</p>
    <ul>
      <li>Clear your browser&apos;s Local Storage</li>
      <li>Disconnect your trackers within the App</li>
      <li>Uninstall or stop using the App</li>
      <li>Revoke access permissions in your Jira/Yandex Tracker accounts</li>
    </ul>

    <h2>10. Children&apos;s Privacy</h2>
    <p>
      The App is intended for business and professional use and is not directed to children. We do not knowingly collect
      personal data from children.
    </p>

    <h2>11. Changes to This Privacy Policy</h2>
    <p>
      We may update this Privacy Policy from time to time to reflect changes in our practices, legal requirements, or
      service functionality. We encourage you to review this policy periodically for any updates.
    </p>

    <h2>12. Contact Information</h2>
    <p>
      If you have questions about this Privacy Policy or the App&apos;s data practices, you can contact us through the
      App&apos;s support channels or documentation.
    </p>
  </main>
);
