name: Release Notes
on:
  pull_request:
    branches: 
      - 'master'
jobs:
  release_notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate release notes
        uses: evrone-erp/release-notes-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          yandex_org_id: ${{ secrets.YANDEX_ORG_ID }}
          yandex_oauth2_token: ${{ secrets.YANDEX_OAUTH2_TOKEN }}
